[
{ "autoconf": {
    "name": "mpfr_conf",
    "configure_args" : [ "--with-gmp-include=$ROOT_DIR/$GMP_INCLUDE",
                         "--with-gmp-lib=$ROOT_DIR/$GMP_LIB"
    ],
    "dependencies": [ "../../gmp:gmp" ],
    "outs": [
       "$GEN_DIR/lib/libmpfr.a"
     ],
    "licenses": [ "http://opensource.org/licenses/gpl-3.0",
                  "http://opensource.org/licenses/lgpl-3.0" ]
} }
]